### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by zetaab** [tarosky/k8s-redis-ha#10]
What is this 
https://github.com/tarosky/k8s-redis-ha/blob/master/example/sentinel.yaml

"library/redis:3.2" and where its dockerfile can be found? It cannot be just like this https://github.com/tarosky/k8s-redis-ha/blob/master/images/sentinel/Dockerfile because it does not contain redis stuff. 

Also, why this initcontainer thing is needed?
```
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
            "name": "k8s-redis-ha-server",
            "image": "tarosky/k8s-redis-ha:server-2.0.0",
            "volumeMounts": [{"name": "opt", "mountPath": "/opt"}]
          }]'
```
it does not do anything else than mount drive?

**Comment by harai** [comment]
I'm not sure why it caused the error.  However, the leading `library/` is redundant and you can freely remove it.

In this Pod, Init Container is used to setup environment to run Redis Sentinels and a related bash script by copying executable files and a config.  Of course, you can do the same things by extending the Redis image.  However, extending the image itself is not really a good practice now Init Container exists.

**Comment by harai** [comment]
Feel free to reopen if you have any other questions.
